Hide and Leather Cap data
Guillaume-Docquier/guillaume-docquier.github.io pull request #20
Opened 2021-06-14 21:58 UTC by UpemGit

Created all data for Hides, Metal Rivets, and Leather Cap

2021-06-14 22:42 UTC, Guillaume-Docquier requested changes
Good PR! Few things to change, mainly related to naming things.

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/hide/durable.js
> +export class Durable extends Hide {
We'll try and call the items exactly as they're called in the game. So here, we would call it DurableHide (and also change to "durableHide" and "durable hide" in the constructor)

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/hide/durable.js
> +export class Durable extends Hide {
Also don't forget to rename the file

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/leather-cap.js
> +import { Item, CraftingMaterial, Rarities, Professions } from "../item";
Try importing from "item" in this fashion: `import {...} from "components/crafting/data/item";`
I know it's not your fault, you probably copy pasted my own code.

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/leather-squares.js
> +            "limberCorium",
Try to always have this field match the class name, but starting with lowerCapped letter. It's important because we're doing some magic with it that will not work if it doesn't match. So here it should read `"limberCoriumLeatherSquares"`

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +        return "any";
Here the effect should read `"out of combat health regeneration"`

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +            "metal rivets (any)",
Since metal rivets don't seem to have a name, like scales or leather squares do, use the effect as name, like you did with stealth. So here it would be `"metal rivets (out of combat health regeneration)"`

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +        return "any";
I'm not even sure if white quality any mats gives you get OOCHR? Could you validate this please?

2021-06-14 22:42 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +class AnyMetalRivets extends MetalRivets {
I think if we called the class `OutOfCombatHealthRegenMetalRivets` it would be more obvious what they do. (Don't forget to change the id `"anyMetalRivets"` to `"outOfCombatHealthRegenMetalRivets"`)

2021-06-14 23:29 UTC, UpemGit commented on src/crowcraft/src/components/crafting/data/items/hide/durable.js
> +export class Durable extends Hide {
This should have been obvious to me.  Also, I assume the file name changes to durable-hide.js, strong-hide.js, etc etc?

2021-06-14 23:29 UTC, UpemGit commented on src/crowcraft/src/components/crafting/data/items/leather-cap.js
> +import { Item, CraftingMaterial, Rarities, Professions } from "../item";
Should I use full paths for all imports or just item?

2021-06-14 23:43 UTC, UpemGit commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +        return "any";
On Winterblade rivets have an Effect 1 and 2.  
![any](https://user-images.githubusercontent.com/85868363/121972126-f3b08e00-cd3f-11eb-87bf-e097864b2b96.png)

Are the effects based on mat quality? Effect 1 = white-green, Effect 2 = blue-orange?

2021-06-15 01:24 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/hide/durable.js
> +export class Durable extends Hide {
That's right! `durable-hide.js` and so on

2021-06-15 01:27 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/leather-cap.js
> +import { Item, CraftingMaterial, Rarities, Professions } from "../item";
For files at the same level or deeper, you'll generally use relative paths (`./file-or-folder`) but when going up (`../something`), use an absolute path. The root folder is considered to be `src/`, so `components/`, `utils/` and `assets/` are at the root.

2021-06-15 01:28 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +        return "any";
We'll have to test in game, because I suspect white-green rivets have OOCHR

2021-06-15 01:38 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +        return "any";
Yeah white-green rivets get OOCHR
Blue doesn't get any benefit. I crafted blue stealth and blue any. Same OOCHR, but blue stealth has an additional stealth bonus.

2021-06-15 02:11 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/leather-squares.js
> +            "CoriumLeatherSquares",
The first letter needs to be lower cased

2021-06-15 02:11 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/leather-squares.js
> +            "ChamoiseLeatherSquares",
The first letter needs to be lower cased

2021-06-15 02:12 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/leather-squares.js
> +import { Hide, Soft, Strong, Tough, Durable, Flexible } from "./hide";
The imports and their uses need to be updated to match the new name (`SoftHide` and so on)

2021-06-15 02:14 UTC, Guillaume-Docquier commented on src/crowcraft/src/components/crafting/data/items/metal-rivets.js
> +            new AnyMetalRivets(),
This one needs to be changed to reflect the rename

2021-06-28 23:18 UTC, Guillaume-Docquier commented
I'll close this because we now generate items files automatically from raw data.

2021-06-28 23:18 UTC, closed without merging